name: rustfmt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Run format check
      run: cargo fmt -- --check
